- name: Download RHEL ISO Package
  hosts: localhost
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Include package downloader role
      ansible.builtin.include_role:
        name: package-downloader
      vars:
        rh_product_filename: rhel.iso
        rh_product_checksum: "{{ checksum.rhel8 if ( rhel_version | int == 8 ) else checksum.rhel9 }}"
        rh_api_offline_token: "{{ offline_token }}"
      when: offline_token is defined and offline_token != ""

- name: This play provisions VMs for RHEL demos
  hosts: localhost
  become: true
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Provision libvirt VM using role
      ansible.builtin.include_role:
        name: host-provisioner
      vars:
        host_modules: "{{ modules }}"
        host_domain: "{{ domain }}"
        host_tf_vars:
          network_cidr: ' ["{{ network_cidr }}"]'

    - name: Add servers to inventory
      ansible.builtin.add_host:
        hostname: "{{ item.hostname }}.{{ domain }}"
        ansible_user: sysadmin
        ansible_ssh_pass: redhat
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        groups:
          - "servers"
      loop: "{{ modules }}"

- name: Check connection to servers
  hosts: servers
  gather_facts: false
  tasks:
    - name: Waiting for installation to end, it can take time!
      ansible.builtin.wait_for_connection:
        timeout: 1800
        sleep: 120

    - name: Ping host to check status
      ansible.builtin.ping:

    - name: Setup is ready
      ansible.builtin.debug:
        msg: "Setup completed, now you can proceed with post install steps"
